// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsvIGfOA6JUE28katk6F2nwLrqatC_abg',
    appId: '1:681609208614:web:caf8b182c702b6fb3dd7e7',
    messagingSenderId: '681609208614',
    projectId: 'taskmate-8ab5f',
    authDomain: 'taskmate-8ab5f.firebaseapp.com',
    databaseURL: 'https://taskmate-8ab5f-default-rtdb.firebaseio.com',
    storageBucket: 'taskmate-8ab5f.appspot.com',
    measurementId: 'G-E69JHKB68V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrikKfirMjNKmy4KPM2OrLLIajlyyrY7w',
    appId: '1:681609208614:android:27758562f8f0c0dd3dd7e7',
    messagingSenderId: '681609208614',
    projectId: 'taskmate-8ab5f',
    databaseURL: 'https://taskmate-8ab5f-default-rtdb.firebaseio.com',
    storageBucket: 'taskmate-8ab5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUbHKcDvDL7W72WlpjwbwJCxVlV6co6_c',
    appId: '1:681609208614:ios:bdf54e73d625f06c3dd7e7',
    messagingSenderId: '681609208614',
    projectId: 'taskmate-8ab5f',
    databaseURL: 'https://taskmate-8ab5f-default-rtdb.firebaseio.com',
    storageBucket: 'taskmate-8ab5f.appspot.com',
    iosClientId: '681609208614-9f6miom5v6leeed7peq4u1k7asapiulv.apps.googleusercontent.com',
    iosBundleId: 'com.taskmateapp.taskmate',
  );
}
