// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAANpKupM2a1jEQDCEVuyuc2kxCSPaYdI',
    appId: '1:143442704256:web:83303839155b9bf594f365',
    messagingSenderId: '143442704256',
    projectId: 'taskmate-d603f',
    authDomain: 'taskmate-d603f.firebaseapp.com',
    storageBucket: 'taskmate-d603f.appspot.com',
    measurementId: 'G-XLKY0L36PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTUSKEtNOPvKxhcTzDP6GKHWPmOYxwn6g',
    appId: '1:143442704256:android:a92db3dd4116d3f194f365',
    messagingSenderId: '143442704256',
    projectId: 'taskmate-d603f',
    storageBucket: 'taskmate-d603f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ7GDVWfveQ0zOginQENRwGpuzw8E_Wng',
    appId: '1:143442704256:ios:48c5b0329a9acd3894f365',
    messagingSenderId: '143442704256',
    projectId: 'taskmate-d603f',
    storageBucket: 'taskmate-d603f.appspot.com',
    iosBundleId: 'com.taskmateapp.taskmate',
  );
}
